spring:
  application:
    name: IKMPGU

  datasource:
    url: jdbc:postgresql://localhost:5432/lab
    username: postgres
    password: 31702005
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080